services:

  db:
    container_name: postgresql_db
    image: postgres:14.6
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=timetable
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  app:
    container_name: app
    build: .
    command: bash -c "python3.11 sql/models.py createdb && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    environment:
      - DATABASE=postgresql
      - DB_USER=user
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=timetable
      - DB_HOST=db
      - EMAIL=${EMAIL} # *@mail.ru
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - PASSWORD_SALT=${PASSWORD_SALT} # openssl rand -hex 32
      - SECRET_KEY=${SECRET_KEY} # openssl rand -hex 32

volumes:
  pgdbdata: null
