"""add model 'PassChangeRequest'

Revision ID: 0416cd6b76f7
Revises: 6c19352b781c
Create Date: 2023-01-12 13:04:02.794937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0416cd6b76f7'
down_revision = '6c19352b781c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass_change_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('new_password', sa.String(length=150), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pass_change_request_id'), 'pass_change_request', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pass_change_request_id'), table_name='pass_change_request')
    op.drop_table('pass_change_request')
    # ### end Alembic commands ###
