"""fix

Revision ID: 0a0e69623259
Revises: f8d868745550
Create Date: 2022-12-25 13:04:50.299805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0e69623259'
down_revision = 'f8d868745550'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('id_user', sa.Integer(), nullable=False))
    op.drop_constraint('application_id_elder_fkey', 'application', type_='foreignkey')
    op.drop_constraint('application_id_user_to_add_fkey', 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'user', ['id_user'], ['id'])
    op.drop_column('application', 'id_elder')
    op.drop_column('application', 'id_user_to_add')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('id_user_to_add', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('application', sa.Column('id_elder', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key('application_id_user_to_add_fkey', 'application', 'user', ['id_user_to_add'], ['id'])
    op.create_foreign_key('application_id_elder_fkey', 'application', 'user', ['id_elder'], ['id'])
    op.drop_column('application', 'id_user')
    # ### end Alembic commands ###
