"""fix

Revision ID: 0cec94af8647
Revises: d638bf1ce271
Create Date: 2022-12-25 12:41:27.518769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cec94af8647'
down_revision = 'd638bf1ce271'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
