"""add cascades

Revision ID: 0f04bdb13173
Revises: ed36b450b5db
Create Date: 2022-12-23 19:10:14.592156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f04bdb13173'
down_revision = 'ed36b450b5db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
