"""fix

Revision ID: 15473b8e5f8e
Revises: 8b64aec8b274
Create Date: 2022-12-25 12:53:08.694175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15473b8e5f8e'
down_revision = '8b64aec8b274'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
