"""fix

Revision ID: 182c49475dc2
Revises: 627cee3dc691
Create Date: 2022-12-25 12:11:12.098180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182c49475dc2'
down_revision = '627cee3dc691'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
