"""add cascade to model 'Application'

Revision ID: 627cee3dc691
Revises: fe18f6ad3c8e
Create Date: 2022-12-25 12:10:03.101058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627cee3dc691'
down_revision = 'fe18f6ad3c8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('application_id_timetable_fkey', 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'timetable', ['id_timetable'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key('application_id_timetable_fkey', 'application', 'timetable', ['id_timetable'], ['id'])
    # ### end Alembic commands ###
