"""create user model

Revision ID: 63924e25592f
Revises: 
Create Date: 2022-12-17 11:57:34.909721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63924e25592f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('education_level', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_specialization_id'), 'specialization', ['id'], unique=False)
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_id'), 'university', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('registry_date', sa.DateTime(), nullable=True),
    sa.Column('tg_username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id_university', sa.Integer(), nullable=False),
    sa.Column('id_specialization', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_specialization'], ['specialization.id'], ),
    sa.ForeignKeyConstraint(['id_university'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_id'), 'timetable', ['id'], unique=False)
    op.create_table('lower_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_timetable', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_timetable'], ['timetable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lower_week_id'), 'lower_week', ['id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_timetable', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_timetable'], ['timetable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_table('timetable_user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_timetable', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_timetable'], ['timetable.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_timetable')
    )
    op.create_index(op.f('ix_timetable_user_id_timetable'), 'timetable_user', ['id_timetable'], unique=False)
    op.create_index(op.f('ix_timetable_user_id_user'), 'timetable_user', ['id_user'], unique=False)
    op.create_table('upper_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_timetable', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_timetable'], ['timetable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upper_week_id'), 'upper_week', ['id'], unique=False)
    op.create_table('lower_day_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lower_week', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_lower_week'], ['lower_week.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lower_day_subjects_id'), 'lower_day_subjects', ['id'], unique=False)
    op.create_table('task_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_task', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_task'], ['task.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_statuses_id'), 'task_statuses', ['id'], unique=False)
    op.create_table('upper_day_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_upper_week', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_upper_week'], ['upper_week.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upper_day_subjects_id'), 'upper_day_subjects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upper_day_subjects_id'), table_name='upper_day_subjects')
    op.drop_table('upper_day_subjects')
    op.drop_index(op.f('ix_task_statuses_id'), table_name='task_statuses')
    op.drop_table('task_statuses')
    op.drop_index(op.f('ix_lower_day_subjects_id'), table_name='lower_day_subjects')
    op.drop_table('lower_day_subjects')
    op.drop_index(op.f('ix_upper_week_id'), table_name='upper_week')
    op.drop_table('upper_week')
    op.drop_index(op.f('ix_timetable_user_id_user'), table_name='timetable_user')
    op.drop_index(op.f('ix_timetable_user_id_timetable'), table_name='timetable_user')
    op.drop_table('timetable_user')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_lower_week_id'), table_name='lower_week')
    op.drop_table('lower_week')
    op.drop_index(op.f('ix_timetable_id'), table_name='timetable')
    op.drop_table('timetable')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_university_id'), table_name='university')
    op.drop_table('university')
    op.drop_index(op.f('ix_specialization_id'), table_name='specialization')
    op.drop_table('specialization')
    # ### end Alembic commands ###
