"""fix

Revision ID: 6b21979921a0
Revises: 15473b8e5f8e
Create Date: 2022-12-25 12:56:28.385225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b21979921a0'
down_revision = '15473b8e5f8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('application_id_elder_fkey', 'application', type_='foreignkey')
    op.drop_column('application', 'id_elder')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('id_elder', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('application_id_elder_fkey', 'application', 'user', ['id_elder'], ['id'])
    # ### end Alembic commands ###
