"""add creation date to model 'Task'

Revision ID: 6c19352b781c
Revises: f366ec9fbc5c
Create Date: 2023-01-08 12:42:36.856944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c19352b781c'
down_revision = 'f366ec9fbc5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('creation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'creation_date')
    # ### end Alembic commands ###
