"""fix

Revision ID: 8b64aec8b274
Revises: 0cec94af8647
Create Date: 2022-12-25 12:44:42.629348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b64aec8b274'
down_revision = '0cec94af8647'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
