"""add outgoing and incoming applications in model 'User'

Revision ID: 95f5110cf586
Revises: 182c49475dc2
Create Date: 2022-12-25 12:31:19.098839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f5110cf586'
down_revision = '182c49475dc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
