"""add cascades

Revision ID: 9df116391e3d
Revises: 0f04bdb13173
Create Date: 2022-12-23 19:19:54.844321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df116391e3d'
down_revision = '0f04bdb13173'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lower_day_subjects_id_lower_week_fkey', 'lower_day_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'lower_day_subjects', 'lower_week', ['id_lower_week'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lower_week_id_timetable_fkey', 'lower_week', type_='foreignkey')
    op.create_foreign_key(None, 'lower_week', 'timetable', ['id_timetable'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_id_timetable_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'timetable', ['id_timetable'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_statuses_id_task_fkey', 'task_statuses', type_='foreignkey')
    op.create_foreign_key(None, 'task_statuses', 'task', ['id_task'], ['id'], ondelete='CASCADE')
    op.drop_constraint('timetable_user_id_timetable_fkey', 'timetable_user', type_='foreignkey')
    op.create_foreign_key(None, 'timetable_user', 'timetable', ['id_timetable'], ['id'], ondelete='CASCADE')
    op.alter_column('upper_day_subjects', 'id_upper_week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('upper_day_subjects_id_upper_week_fkey', 'upper_day_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'upper_day_subjects', 'upper_week', ['id_upper_week'], ['id'], ondelete='CASCADE')
    op.drop_constraint('upper_week_id_timetable_fkey', 'upper_week', type_='foreignkey')
    op.create_foreign_key(None, 'upper_week', 'timetable', ['id_timetable'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upper_week', type_='foreignkey')
    op.create_foreign_key('upper_week_id_timetable_fkey', 'upper_week', 'timetable', ['id_timetable'], ['id'])
    op.drop_constraint(None, 'upper_day_subjects', type_='foreignkey')
    op.create_foreign_key('upper_day_subjects_id_upper_week_fkey', 'upper_day_subjects', 'upper_week', ['id_upper_week'], ['id'])
    op.alter_column('upper_day_subjects', 'id_upper_week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'timetable_user', type_='foreignkey')
    op.create_foreign_key('timetable_user_id_timetable_fkey', 'timetable_user', 'timetable', ['id_timetable'], ['id'])
    op.drop_constraint(None, 'task_statuses', type_='foreignkey')
    op.create_foreign_key('task_statuses_id_task_fkey', 'task_statuses', 'task', ['id_task'], ['id'])
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_id_timetable_fkey', 'task', 'timetable', ['id_timetable'], ['id'])
    op.drop_constraint(None, 'lower_week', type_='foreignkey')
    op.create_foreign_key('lower_week_id_timetable_fkey', 'lower_week', 'timetable', ['id_timetable'], ['id'])
    op.drop_constraint(None, 'lower_day_subjects', type_='foreignkey')
    op.create_foreign_key('lower_day_subjects_id_lower_week_fkey', 'lower_day_subjects', 'lower_week', ['id_lower_week'], ['id'])
    # ### end Alembic commands ###
