"""add date for model 'Application'

Revision ID: adea5650821f
Revises: ea4dd46a1bfa
Create Date: 2023-01-03 15:16:40.500103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adea5650821f'
down_revision = 'ea4dd46a1bfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('creation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'creation_date')
    # ### end Alembic commands ###
