"""fix

Revision ID: d638bf1ce271
Revises: 95f5110cf586
Create Date: 2022-12-25 12:38:38.790226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd638bf1ce271'
down_revision = '95f5110cf586'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
