"""add dates

Revision ID: ea4dd46a1bfa
Revises: 0a0e69623259
Create Date: 2023-01-03 15:09:56.422013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4dd46a1bfa'
down_revision = '0a0e69623259'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.add_column('timetable_user', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable_user', 'date_added')
    op.drop_column('timetable', 'creation_date')
    # ### end Alembic commands ###
