"""add tags for model 'Task'

Revision ID: f366ec9fbc5c
Revises: adea5650821f
Create Date: 2023-01-07 13:53:07.401563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f366ec9fbc5c'
down_revision = 'adea5650821f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('tag', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'tag')
    # ### end Alembic commands ###
