"""fix

Revision ID: f8d868745550
Revises: 6b21979921a0
Create Date: 2022-12-25 13:00:25.650998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d868745550'
down_revision = '6b21979921a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('id_elder', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'application', 'user', ['id_elder'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_column('application', 'id_elder')
    # ### end Alembic commands ###
