"""add model 'Application'

Revision ID: fe18f6ad3c8e
Revises: 76e16adf33a6
Create Date: 2022-12-25 11:55:30.967887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe18f6ad3c8e'
down_revision = '76e16adf33a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user_to_add', sa.Integer(), nullable=False),
    sa.Column('id_elder', sa.Integer(), nullable=False),
    sa.Column('id_timetable', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_elder'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_timetable'], ['timetable.id'], ),
    sa.ForeignKeyConstraint(['id_user_to_add'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_id'), 'application', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_id'), table_name='application')
    op.drop_table('application')
    # ### end Alembic commands ###
